import {
  decodeImageArtifactId,
  decodeImageGenerationScopeId,
  MAX_GENERATED_IMAGE_BYTES,
  type ImageArtifactId,
  type ImageArtifactMediaType,
  type ImageGenerationScopeId,
} from "@octant/contracts";
import {
  MAX_MANAGED_ATTACHMENT_DISPLAY_NAME_LENGTH,
  ManagedAttachmentStore,
  sanitizeManagedAttachmentDisplayName,
} from "../attachments/managedAttachmentStore";

export { MAX_GENERATED_IMAGE_BYTES };
export const MAX_GENERATED_IMAGE_DISPLAY_NAME_LENGTH = MAX_MANAGED_ATTACHMENT_DISPLAY_NAME_LENGTH;

export class GeneratedImageTooLarge extends Error {
  readonly category = "too-large" as const;

  constructor(readonly byteLength: number) {
    super(
      `Generated image is too large (${byteLength} bytes). The maximum size is ${MAX_GENERATED_IMAGE_BYTES} bytes.`,
    );
    this.name = "GeneratedImageTooLarge";
  }
}

export class GeneratedImageInvalid extends Error {
  readonly category = "invalid" as const;

  constructor(message: string) {
    super(message);
    this.name = "GeneratedImageInvalid";
  }
}

export interface GeneratedImageStaged {
  readonly scopeId: ImageGenerationScopeId;
  readonly attachmentId: ImageArtifactId;
  readonly displayName: string;
  readonly size: number;
  readonly hash: string;
  readonly stagedAt: string;
}

export interface GeneratedImageFinalized {
  readonly scopeId: ImageGenerationScopeId;
  readonly attachmentId: ImageArtifactId;
  readonly displayName: string;
  readonly size: number;
  readonly hash: string;
  readonly mime: ImageArtifactMediaType;
  readonly finalizedAt: string;
}

export interface GeneratedImageRecoveryOptions {
  readonly isFinalizedAttachmentReferenced?: (
    scopeId: ImageGenerationScopeId,
    attachmentId: ImageArtifactId,
  ) => boolean;
}

const PNG_MAGIC = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a] as const;
const JPEG_MAGIC = [0xff, 0xd8, 0xff] as const;
const GIF87 = [0x47, 0x49, 0x46, 0x38, 0x37, 0x61] as const;
const GIF89 = [0x47, 0x49, 0x46, 0x38, 0x39, 0x61] as const;

/**
 * Classify generated bytes by magic number. Provider MIME types and URLs are
 * not consulted: a URL form never reaches this store, and a mismatched type
 * is malformed output rather than an image.
 */
export function sniffGeneratedImageMediaType(
  bytes: Uint8Array,
): ImageArtifactMediaType | undefined {
  if (startsWith(bytes, PNG_MAGIC)) return "image/png";
  if (startsWith(bytes, JPEG_MAGIC)) return "image/jpeg";
  if (startsWith(bytes, GIF87) || startsWith(bytes, GIF89)) return "image/gif";
  if (
    startsWith(bytes, [0x52, 0x49, 0x46, 0x46]) &&
    bytes.length >= 12 &&
    startsWith(bytes, [0x57, 0x45, 0x42, 0x50], 8)
  ) {
    return "image/webp";
  }
  return undefined;
}

function generatedImageManagedStore(dataDirectory: string): ManagedAttachmentStore {
  return new ManagedAttachmentStore(dataDirectory, {
    scopesDirectory: "generated-images",
    maxBytes: MAX_GENERATED_IMAGE_BYTES,
    decodeScopeId: (value) => String(decodeImageGenerationScopeId(value)),
    decodeAttachmentId: (value) => String(decodeImageArtifactId(value)),
    tooLarge: (byteLength) => new GeneratedImageTooLarge(byteLength),
    empty: () => new GeneratedImageInvalid("Generated image must not be empty."),
    invalidDisplayName: (message) => new GeneratedImageInvalid(message),
  });
}

export function sanitizeGeneratedImageDisplayName(name: string): string {
  return sanitizeManagedAttachmentDisplayName(
    name,
    (message) => new GeneratedImageInvalid(message),
  );
}

/**
 * Generated image bytes. Staging, digest-checked finalization, and crash
 * recovery live in the shared managed store; this class is the image-generation
 * boundary that decodes image identities and keeps image error types.
 */
export class GeneratedImageStore {
  readonly #store: ManagedAttachmentStore;

  constructor(dataDirectory: string) {
    this.#store = generatedImageManagedStore(dataDirectory);
  }

  async stage(input: {
    readonly scopeId: ImageGenerationScopeId;
    readonly attachmentId: ImageArtifactId;
    readonly displayName: string;
    readonly bytes: Uint8Array;
    readonly signal?: AbortSignal;
  }): Promise<GeneratedImageStaged> {
    if (input.bytes.length === 0) {
      throw new GeneratedImageInvalid("Generated image must not be empty.");
    }
    if (input.bytes.length > MAX_GENERATED_IMAGE_BYTES) {
      throw new GeneratedImageTooLarge(input.bytes.length);
    }
    if (sniffGeneratedImageMediaType(input.bytes) === undefined) {
      throw new GeneratedImageInvalid("Generated bytes are not a recognized image.");
    }
    const staged = await this.#store.stage({
      scopeId: String(input.scopeId),
      attachmentId: String(input.attachmentId),
      displayName: input.displayName,
      bytes: input.bytes,
      ...(input.signal === undefined ? {} : { signal: input.signal }),
    });
    return {
      scopeId: decodeImageGenerationScopeId(staged.scopeId),
      attachmentId: decodeImageArtifactId(staged.attachmentId),
      displayName: staged.displayName,
      size: staged.size,
      hash: staged.hash,
      stagedAt: staged.stagedAt,
    };
  }

  async finalize(staged: GeneratedImageStaged): Promise<GeneratedImageFinalized> {
    const finalized = await this.#store.finalize({
      scopeId: String(staged.scopeId),
      attachmentId: String(staged.attachmentId),
      displayName: staged.displayName,
      size: staged.size,
      hash: staged.hash,
      stagedAt: staged.stagedAt,
    });
    const bytes = await this.#store.read(finalized);
    const mime = sniffGeneratedImageMediaType(bytes);
    if (mime === undefined) {
      throw new GeneratedImageInvalid("Finalized bytes are not a recognized image.");
    }
    return {
      scopeId: decodeImageGenerationScopeId(finalized.scopeId),
      attachmentId: decodeImageArtifactId(finalized.attachmentId),
      displayName: finalized.displayName,
      size: finalized.size,
      hash: finalized.hash,
      mime,
      finalizedAt: finalized.finalizedAt,
    };
  }

  read(finalized: GeneratedImageFinalized): Promise<Uint8Array> {
    return this.#store.read({
      scopeId: String(finalized.scopeId),
      attachmentId: String(finalized.attachmentId),
      displayName: finalized.displayName,
      size: finalized.size,
      hash: finalized.hash,
      finalizedAt: finalized.finalizedAt,
    });
  }

  remove(scopeId: ImageGenerationScopeId, attachmentId: ImageArtifactId): Promise<void> {
    return this.#store.remove(String(scopeId), String(attachmentId));
  }

  recover(options: GeneratedImageRecoveryOptions = {}): Promise<void> {
    const isReferenced = options.isFinalizedAttachmentReferenced;
    return this.#store.recover(
      isReferenced === undefined
        ? {}
        : {
            isFinalizedAttachmentReferenced: (scopeId, attachmentId) =>
              isReferenced(
                decodeImageGenerationScopeId(scopeId),
                decodeImageArtifactId(attachmentId),
              ),
          },
    );
  }

  hasTemporaryFiles(): Promise<boolean> {
    return this.#store.hasTemporaryFiles();
  }

  purgeScope(scopeId: ImageGenerationScopeId): Promise<void> {
    return this.#store.purgeScope(String(scopeId));
  }
}

function startsWith(bytes: Uint8Array, magic: ReadonlyArray<number>, offset = 0): boolean {
  if (bytes.length < offset + magic.length) return false;
  return magic.every((value, index) => bytes[offset + index] === value);
}
