#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO="Ogard-Labs/octant"
RINGS=(preview stable)
# Nothing captured here is written to disk. A Developer ID password or a feed
# signing key in a .env file is a private key sitting in the working tree, and
# the wizard exists to move these into GitHub, not to keep a second copy.
ENV_FILE="$(mktemp -d)/unused.env"

# set_env_secret NAME VALUE puts one secret in every release environment.
# The library's set_secret writes a repository secret, which any workflow on
# any branch can read; these belong to the environments, whose branch and tag
# policies are what keep a side branch from reading the signing key.
set_env_secret() {
  local name="$1" value="$2" ring
  for ring in "${RINGS[@]}"; do
    if printf '%s' "$value" | gh secret set "$name" --repo "$REPO" --env "$ring" >/dev/null 2>&1; then
      printf '  %s✓ set%s %s in the %s environment\n' "$GREEN" "$RESET" "$name" "$ring"
    else
      SKIPPED+=("secret $name in $ring (gh secret set $name --repo $REPO --env $ring)")
      warn "could not set $name in $ring"
    fi
  done
  WRITTEN_SECRET+=("$name")
}

set_repo_var() {
  local name="$1" value="$2"
  if gh variable set "$name" --repo "$REPO" --body "$value" >/dev/null 2>&1; then
    printf '  %s✓ set%s variable %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("variable $name (gh variable set $name --repo $REPO --body ...)")
    warn "could not set variable $name"
  fi
}

banner "Octant release credentials"

# ──────────────────────────────────────────────────────────────────────────
stage "Check the tools this needs"
say "Nothing is changed in this stage; it only checks what the rest relies on."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is missing or signed out. Run: gh auth login"
  exit 1
fi
if ! gh api "repos/${REPO}" --jq '.permissions.admin' | grep -q true; then
  warn "This account is not an admin of ${REPO}, so it cannot write environment secrets."
  exit 1
fi
for tool in openssl ssh-keygen security base64; do
  command -v "$tool" >/dev/null 2>&1 || { warn "missing required tool: $tool"; exit 1; }
done
say "GitHub CLI is authenticated and this account administers ${REPO}."
note "Environments preview and stable already exist, with stable gated on your approval."
pause "Press Enter to begin."

# ──────────────────────────────────────────────────────────────────────────
stage "Apple: create a Developer ID Application certificate"
say "This is the one that signs a release. An 'Apple Development' certificate"
say "cannot be notarized for distribution, so a new certificate is needed even"
say "if you already sign builds locally."
say ""
step "Open Keychain Access → menu Keychain Access → Certificate Assistant →"
step "  Request a Certificate From a Certificate Authority."
step "Enter your email, leave CA Email blank, choose 'Saved to disk', and save"
step "  the .certSigningRequest file."
open_url "https://developer.apple.com/account/resources/certificates/add"
step "On the page just opened, choose 'Developer ID Application', continue,"
step "  upload the .certSigningRequest, then download the .cer file."
step "Double-click the downloaded .cer to install it into your login keychain."
pause "Press Enter once the certificate is installed."

DEVELOPER_ID_IDENTITY=$(security find-identity -v -p codesigning 2>/dev/null \
  | grep "Developer ID Application" | head -1 | sed -E 's/.*"(.*)".*/\1/') || true
if [[ -z "$DEVELOPER_ID_IDENTITY" ]]; then
  warn "No 'Developer ID Application' identity is visible in your keychain yet."
  ask DEVELOPER_ID_IDENTITY "Type the identity name exactly as Keychain Access shows it:"
else
  say "Found: ${DEVELOPER_ID_IDENTITY}"
fi
set_repo_var OCTANT_SIGNING_IDENTITY "$DEVELOPER_ID_IDENTITY"

# ──────────────────────────────────────────────────────────────────────────
stage "Apple: export the certificate for the build runner"
say "GitHub's runner has no keychain of yours, so it needs the certificate and"
say "its private key as a password-protected .p12, base64 encoded."
say ""
step "In Keychain Access, find '${DEVELOPER_ID_IDENTITY}' under My Certificates."
step "Right-click it → Export → format 'Personal Information Exchange (.p12)'."
step "Choose a strong password when it asks; you will paste it below."
ask P12_PATH "Full path to the exported .p12 file:"
P12_PATH="${P12_PATH/#\~/$HOME}"
if [[ ! -f "$P12_PATH" ]]; then
  warn "No file at ${P12_PATH}. Re-run this wizard once it is exported."
  exit 1
fi
ask_secret P12_PASSWORD "The password you gave that .p12:"
set_env_secret OCTANT_SIGNING_CERTIFICATE_P12 "$(base64 < "$P12_PATH" | tr -d '\n')"
set_env_secret OCTANT_SIGNING_CERTIFICATE_PASSWORD "$P12_PASSWORD"
say ""
if confirm "Delete ${P12_PATH} now that GitHub has it?"; then
  rm -f "$P12_PATH"
  say "Deleted. Your keychain still holds the certificate."
else
  warn "Keep it somewhere private, and out of any repository."
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Apple: create a notarization key"
say "Notarization is Apple checking the signed app. It authenticates with an"
say "App Store Connect API key rather than your Apple ID password."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Open the 'Integrations' tab, then 'Keys'."
step "Create a key with the 'Developer' role, or reuse one you already have."
step "Copy the Issuer ID shown above the table."
ask NOTARY_ISSUER_ID "Issuer ID:"
step "Copy the Key ID from the key's row, then download its .p8 file."
note "Apple lets you download a .p8 exactly once."
ask NOTARY_KEY_ID "Key ID:"
ask NOTARY_KEY_PATH "Full path to the downloaded .p8 file:"
NOTARY_KEY_PATH="${NOTARY_KEY_PATH/#\~/$HOME}"
if [[ ! -f "$NOTARY_KEY_PATH" ]]; then
  warn "No file at ${NOTARY_KEY_PATH}."
  exit 1
fi
set_repo_var OCTANT_NOTARY_ISSUER_ID "$NOTARY_ISSUER_ID"
set_repo_var OCTANT_NOTARY_KEY_ID "$NOTARY_KEY_ID"
set_env_secret OCTANT_NOTARY_KEY "$(cat "$NOTARY_KEY_PATH")"
note "Keep the .p8 somewhere private; Apple will not give it to you again."

# ──────────────────────────────────────────────────────────────────────────
stage "Octant: mint the update feed signing key"
say "This key is what makes an update trustworthy. The app verifies every feed"
say "against the public half compiled into it, so nothing a server sends can"
say "install without this key having signed it."
warn "Its loss means re-releasing; its compromise means code execution on every"
warn "install. Keep the private half only in GitHub and in your own backup."
say ""
FEED_KEY_DIR=$(mktemp -d)
chmod 700 "$FEED_KEY_DIR"
# PKCS8 DER for the private half and SPKI DER for the public half: the same
# encodings scripts/sign-update-feed.ts and the app's verifier expect.
openssl genpkey -algorithm ed25519 -outform DER -out "${FEED_KEY_DIR}/feed.der" 2>/dev/null
openssl pkey -inform DER -in "${FEED_KEY_DIR}/feed.der" -pubout -outform DER \
  -out "${FEED_KEY_DIR}/feed.pub.der" 2>/dev/null
FEED_PUBLIC_KEY=$(base64 < "${FEED_KEY_DIR}/feed.pub.der" | tr -d '\n')
set_env_secret OCTANT_UPDATE_FEED_PRIVATE_KEY "$(base64 < "${FEED_KEY_DIR}/feed.der" | tr -d '\n')"
rm -rf "$FEED_KEY_DIR"
say ""
say "Public half (this belongs in the source, and is not secret):"
say "  ${FEED_PUBLIC_KEY}"
FEED_SOURCE="apps/desktop/src/appUpdateFeed.ts"
if [[ -f "$FEED_SOURCE" ]] && confirm "Write it into ${FEED_SOURCE} now?"; then
  /usr/bin/sed -i '' \
    "s|^export const OCTANT_UPDATE_PUBLIC_KEY = .*|export const OCTANT_UPDATE_PUBLIC_KEY = \"${FEED_PUBLIC_KEY}\";|" \
    "$FEED_SOURCE"
  say "Written. Commit that change — until it ships, builds verify nothing and offer no updates."
else
  SKIPPED+=("set OCTANT_UPDATE_PUBLIC_KEY in ${FEED_SOURCE} to ${FEED_PUBLIC_KEY}")
fi

# ──────────────────────────────────────────────────────────────────────────
stage "octant.sh: a deploy key for publishing the feed"
say "The workflow copies one signed JSON file per ring to your server. It needs"
say "an SSH key that can write only that directory."
ask FEED_SSH_USER "SSH user on octant.sh:"
ask FEED_REMOTE_PATH "Directory the feed is served from (e.g. /var/www/octant.sh/updates):"
set_repo_var OCTANT_FEED_SSH_USER "$FEED_SSH_USER"
set_repo_var OCTANT_FEED_REMOTE_PATH "$FEED_REMOTE_PATH"
DEPLOY_KEY_DIR=$(mktemp -d)
chmod 700 "$DEPLOY_KEY_DIR"
ssh-keygen -t ed25519 -N "" -C "octant-release-feed" -f "${DEPLOY_KEY_DIR}/id" -q
say ""
say "Add this public key to ${FEED_SSH_USER}@octant.sh in ~/.ssh/authorized_keys:"
say ""
say "  $(cat "${DEPLOY_KEY_DIR}/id.pub")"
say ""
note "Worth restricting: prefix the line with 'restrict,' so the key cannot"
note "open a shell, and if you want it narrowed to one directory, rrsync"
note "(shipped with rsync) is the tool built for that."
pause "Press Enter once the key is installed on the server."
set_env_secret OCTANT_FEED_SSH_KEY "$(cat "${DEPLOY_KEY_DIR}/id")"
rm -rf "$DEPLOY_KEY_DIR"

# ──────────────────────────────────────────────────────────────────────────
stage "Prove it before trusting it"
say "Everything is in place. Two things are worth checking now rather than"
say "during a release."
say ""
step "Confirm the host key GitHub will pin matches your server. On octant.sh run:"
step "  ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub"
step "and compare it with:"
say "  $(gh variable get OCTANT_FEED_SSH_KNOWN_HOSTS --repo "$REPO" 2>/dev/null | ssh-keygen -lf /dev/stdin 2>/dev/null || echo 'set OCTANT_FEED_SSH_KNOWN_HOSTS first')"
say ""
step "Then run a preview build by hand and watch it through:"
step "  gh workflow run 'Release (preview)' --repo ${REPO} -f force=true"
say ""
note "A stable release is a tag: bump the version in scripts/package-desktop.ts,"
note "then push v<that version>. It waits for your approval before it signs."

finish
